package com.xhp.crowdfunding.dao;

import com.xhp.crowdfunding.entity.Approval;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ApprovalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbg.generated
     */
    int insert(Approval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbg.generated
     */
    Approval selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbg.generated
     */
    List<Approval> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Approval record);
}