package com.xhp.crowdfunding.dao;

import com.xhp.crowdfunding.entity.Homecarousel;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface HomecarouselMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homecarousel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homecarousel
     *
     * @mbg.generated
     */
    int insert(Homecarousel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homecarousel
     *
     * @mbg.generated
     */
    Homecarousel selectByPrimaryKey(String hcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homecarousel
     *
     * @mbg.generated
     */
    List<Homecarousel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homecarousel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Homecarousel record);
}