package com.xhp.crowdfunding.dao;

import com.xhp.crowdfunding.entity.Projectclassification;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ProjectclassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String pcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int insert(Projectclassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    Projectclassification selectByPrimaryKey(String pcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    List<Projectclassification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectclassification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Projectclassification record);
}