server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crowdfunding
    username: root
    password: 1234
mybatis:
  type-aliases-package: com.xhp.crowdfunding.entity
  mapperLocations: classpath:mapper/**/*.xml
logging:
  level:
    com.octopus.mybatistest.dao: DEBUG