package com.xhp.crowdfunding.entity;

import lombok.Data;

import java.util.Date;

@Data
public class Approval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Aid
     *
     * @mbg.generated
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Astate
     *
     * @mbg.generated
     */
    private String astate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.Adate
     *
     * @mbg.generated
     */
    private Date adate;

}