package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Ccontext
     *
     * @mbg.generated
     */
    private String ccontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CreplyId
     *
     * @mbg.generated
     */
    private String creplyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Pid
     *
     * @mbg.generated
     */
    private String pid;

}