package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class Homecarousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homecarousel.HCid
     *
     * @mbg.generated
     */
    private String hcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homecarousel.HCimage
     *
     * @mbg.generated
     */
    private String hcimage;

}