package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Oid
     *
     * @mbg.generated
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Ostate
     *
     * @mbg.generated
     */
    private String ostate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Omoney
     *
     * @mbg.generated
     */
    private Integer omoney;
}