package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pid
     *
     * @mbg.generated
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.paccountName
     *
     * @mbg.generated
     */
    private String paccountname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pidentify
     *
     * @mbg.generated
     */
    private String pidentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.paccountTel
     *
     * @mbg.generated
     */
    private String paccounttel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ploc
     *
     * @mbg.generated
     */
    private String ploc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pimage
     *
     * @mbg.generated
     */
    private String pimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pcontent
     *
     * @mbg.generated
     */
    private String pcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pdate
     *
     * @mbg.generated
     */
    private String pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ptargetMoney
     *
     * @mbg.generated
     */
    private Integer ptargetmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.praiseDays
     *
     * @mbg.generated
     */
    private Integer praisedays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ppresentMoney
     *
     * @mbg.generated
     */
    private Integer ppresentmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ptags
     *
     * @mbg.generated
     */
    private String ptags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pdescripTitle
     *
     * @mbg.generated
     */
    private String pdescriptitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pdescripCont
     *
     * @mbg.generated
     */
    private String pdescripcont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.prepayType
     *
     * @mbg.generated
     */
    private String prepaytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.prepayTitle
     *
     * @mbg.generated
     */
    private String prepaytitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.prepayCont
     *
     * @mbg.generated
     */
    private String prepaycont;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pcid
     *
     * @mbg.generated
     */
    private Integer pcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.uid
     *
     * @mbg.generated
     */
    private Integer uid;

}