package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class Projectclassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectclassification.Pcid
     *
     * @mbg.generated
     */
    private String pcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectclassification.Pcname
     *
     * @mbg.generated
     */
    private String pcname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectclassification.Pcnumber
     *
     * @mbg.generated
     */
    private Integer pcnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectclassification.Pcimage
     *
     * @mbg.generated
     */
    private String pcimage;
}