package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class Sponsor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor.Sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor.Sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor.Smoney
     *
     * @mbg.generated
     */
    private Integer smoney;

}