package com.xhp.crowdfunding.entity;

import lombok.Data;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.unickname
     *
     * @mbg.generated
     */
    private String unickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upassword
     *
     * @mbg.generated
     */
    private String upassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usex
     *
     * @mbg.generated
     */
    private String usex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uidNumber
     *
     * @mbg.generated
     */
    private String uidnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uphone
     *
     * @mbg.generated
     */
    private Integer uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uimage
     *
     * @mbg.generated
     */
    private String uimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbg.generated
     */
    private String uemail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated
     */

}